## base template
#
# todo:
#   - Split into individual tasks
#   - add the following tools:
---
- hosts: localhost
  user: root
  connection: local

  vars:
    user: menztrual

  tasks:
  - name: Add spotify signing key
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=BBEBDCB318AD50EC6865090613B00F1FD2C19886

  - name: Copy spotify.list to /etc/apt/sources.list.d
    copy: src=files/spotify.list dest=/etc/apt/sources.list.d/ owner=root group=root mode=0644

  - name: apt-update
    apt: update_cache=yes

  - name: apt-upgrade
    apt: upgrade=dist

  - name: Install software
    apt: name={{item}} state=latest update_cache=yes force=yes
    with_items:
     - vim
     - i3
     - i3lock
     - i3blocks
     - thunar
     - docker
     - wine
     - wireshark
     - binwalk
     - virtualbox
     - hexchat
     - spotify-client
     - aircrack-ng
     - ghex
     - hydra
     - byzanz
     - arandr
     - dunst
     - compton
     - arduino
     - lxappearance
     - gnome-icon-theme-full
     - rofi
     - pavucontrol
     - scrot
     - feh

  - name: Downloading Google Chrome
    get_url:
      url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dest: /home/{{user}}/Downloads/chrome.deb
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0440

  - name: Installing Google Chrome
    apt: "deb=/home/{{user}}/Downloads/chrome.deb"

  - name: Downloading atom
    get_url:
      url: https://atom.io/download/deb
      dest: /home/{{user}}/Downloads/atom.deb
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0440

  - name: Installing atom
    apt: "deb=/home/{{user}}/Downloads/atom.deb"

  - name: Downloading Dropbox
    get_url:
      url: https://www.dropbox.com/download?dl=packages/debian/dropbox_2015.10.28_amd64.deb
      dest: /home/{{user}}/Downloads/dropbox.deb
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0755

  - name: Installing Dropbox
    apt: "deb=/home/{{user}}/Downloads/dropbox.deb"

  - name: Downloading burp
    get_url:
      url: https://portswigger.net/Burp/Releases/Download?productId=100&version=1.7.06&type=Linux
      dest: /home/{{user}}/Downloads/burp.sh
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0755

  - name: Installing burp
    script: /home/{{user}}/Downloads/burp.sh
 
  - name: Download Slack
    get_url:
      url: https://downloads.slack-edge.com/linux_releases/slack-desktop-2.1.2-amd64.deb
      dest: /home/{{user}}/Downloads/slack.deb
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0755

  - name: Install Slack
    apt: "deb=/home/{{user}}/Downloads/slack.deb"
  
  - name: Copy wallpaper
    copy: src=files/wallpaper.jpg dest=/home/{{user}}/Pictures owner={{user}} group={{user}} mode=0644

  - name: Copy i3 configugration & scripts
    copy: src=files/i3 dest=/home/{{user}}/.config owner={{user}} group={{user}} mode=0644

  - name: Make scripts executable
    file: path=/home/{{user}}/.config/i3/{{item.script }} mode="u+rwx,g-rwx,o-x"
    with_items:
      - { script: 'battery.sh'}
      - { script: 'lock.sh'}
  - name: Copy fonts for i3 theme
    copy: src=files/fonts/ dest=/home/{{user}}/.fonts owner={{user}} group={{user}} mode=0644
  - name: copy .gtkrc-2.0
    copy: src=config/dotgtkrc-2.0 dest=/home/{{user}}/.gtkrc-2.0 owner={{user}} group={{user}} mode=0644   
  - name: Copy gtk-3.0 folder into .config for font config
    copy: src=config/gtk-3.0 dest=/home/{{user}}/.config/ owner={{user}} group={{user}} mode=0644

  - name: Copy Xresources for Rofi theme
    copy: src=files/dotXresources dest=/home/{{user}}/.Xresources owner={{user}} group={{user}} mode=0644
